version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://meallog:password@db:5432/meallog
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET_KEY=development-secret-key-change-in-production
      - ENVIRONMENT=development
      - DEBUG=true
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    command: uv run uvicorn src.main:app --reload --host 0.0.0.0 --port 8000

  db:
    image: postgis/postgis:15-3.3
    environment:
      - POSTGRES_USER=meallog
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=meallog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: